### PR TITLE
Investigate debug logs of ecchronos - Issue #533

### PR DESCRIPTION
**Pull request by DanielwEriksson**

### CODE REVIEW

**Review by VictorCavichioli — CHANGES_REQUESTED** [review]
I think maybe you need to add on logback.xml the TRACE level, I think that if you're not doing it the logs will be just ignored.

Please, test it.

**Review by jwaeab — COMMENTED** [review]
A couple of generic questions before dwelling into the actual code review:

- What kind of criteria(s) have you based these changes on?
- Did you check with Mackan what he meant by "throttling"? I see no code/comments relating to this. There is a ThrottlingLogger class in ecChronos, perhaps he meant make use of that more?
- While doing this, have you also checked if any of the other log levels need to be changed in any way (warn, info, error etc)? Perhaps you have traces that actually should be debug etc. But this kind of relates to my first point.
- In a quick read through of the code, I find odd LOGs in general.

**Comment by DanielwEriksson** [comment]
To quote macan when I asked for a Definition of Done for this task.
"DoD är, flytta alla debug loggar som inte hjälper med troubleshooting till trace."
This is just a first suggestion otherwise we have to discuss each debug entry in the log. I have tried to keep those that I think is part of a flow. Those that I think is just some random information I have moved to trace.

**Comment by jwaeab** [comment]
Debug is perhaps more used for isolated events, so those can be debugged more easily. Trace on the other hand is perhaps mostly used when trace execution/flows/request-response-trails/etc.
If something is regarded "random information", then it is probably not useful for either debugging or tracing (or logging to begin with).

**Comment by jwaeab** [comment]
Part of this will be done in issue #666

**Pull request closed without merging**
