### PR TITLE
Add name field to each maven module

### LINKED ISSUE #371: Populate <name> field in pom.xml files
Hi,

This is more of a request than an actual issue... But, automation that we are using is relying on parsing the pom.xml files, and seems to be using the <name> field. When this field is not populated, it falls back to <artifactId>. Looking at these in ecChronos, they are all pretty "generic" so to speak, like "application", "core", "fm", and so on. Therefore, they are not very useful.

What I would like is for the <name> fields in each pom.xml to be populated with slightly more descriptive names. If we take the examples above, it would be as easy as having:
 * ecChronos Application
 * ecChronos Core
 * ecChronos Fault Management

Here's another random component to illustrate:
https://github.com/eclipse-ee4j/jaf/blob/master/api/pom.xml

### PR DESCRIPTION
**Pull request by masokol**
Closes #371

### CODE REVIEW

**Review by ch1bbe — APPROVED** [review]

**Comment by itskarlsson** [comment]
@ArcturusMengsk LGTY?

**Comment by ArcturusMengsk** [comment]
I would prefer title capitalization, if possible. According to https://capitalizemytitle.com/, **Chicago** style.
But if it's already merged, then don't bother.

**Comment by masokol** [comment]
@ArcturusMengsk Is this what you had in mind?

**Review by ch1bbe — APPROVED** [review]

**Comment by ArcturusMengsk** [comment]
> @ArcturusMengsk Is this what you had in mind?

Yes, thank you!

**Pull request merged**
