### PR TITLE
New PMD

### PR DESCRIPTION
**Pull request by emolsson**
* Use new PMD version
* Ensure project is compiled before pmd run

### CODE REVIEW

**Review by itskarlsson — COMMENTED** [review]
I'd be in favor of modifying the CloseResource rule so we do not have to add a bunch of NOPMD

**Comment by emolsson** [comment]
I agree. Do you have a suggestion on how that can be done? I tried modifying the rule without success.

I believe this might also be an issue as we do not use try-with-resources or try-finally to close them (we create them at one place and close them somewhere else).

**Comment by emolsson** [comment]
I agree. Do you have a suggestion on how that can be done? I tried modifying the rule without success.

I believe this might also be an issue as we do not use try-with-resources or try-finally to close them (we create them at one place and close them somewhere else).

**Comment by itskarlsson** [comment]
There are some warnings too when building:
```
[WARNING] Unable to exclude rules [InvalidSlf4jMessageFormat] from ruleset reference category/java/errorprone.xml; perhaps the rule name is mispelled or the rule doesn't exist anymore?
[WARNING] Removed misconfigured rule: LoosePackageCoupling  cause: No packages or classes specified
```
Simply add to design
<exclude name="LoosePackageCoupling" />
and remove
<exclude name="InvalidSlf4jMessageFormat" />

**Review by itskarlsson — APPROVED** [review]

**Pull request merged**
